#! /bin/sh

PATH=$HOME/OpenSC/src/tools:$PATH

pattern=4
case $pattern in
    1)
	( dd if=/dev/zero bs=63 count=1; printf "\001" ) > TMP.data
	;;
    2)
	( dd if=/dev/zero bs=63 count=1; printf "\002" ) > TMP.data
	;;
    3)
	( printf "\001"; dd if=/dev/zero bs=63 count=1  ) > TMP.data
	;;
    4)
	( printf "\001"; dd if=/dev/urandom bs=63 count=1 ) > TMP.data
	;;
esac

pkcs15-crypt --pin 1111 --sign --key 45 -i TMP.data --output TMP.signed $*

openssl rsautl -verify -raw -in TMP.signed -inkey ~/sslkeys/test.apebble.com.key -out TMP.recovered

echo "data"
hd -v TMP.data
echo "signed"
hd -v TMP.signed
echo "recovered"
hd -v TMP.recovered

cmp TMP.data TMP.recovered
if [ $? = 0 ]
then
    echo "TMP.data and TMP.recovered match"
fi


